"use client";

import { useState, useCallback, useMemo } from "react";
import { useQuery } from "convex/react";
import { api } from "../../../../convex/_generated/api";
// Note: Id type is generated by Convex. If not available, run `npx convex dev`
type Id<T extends string> = string & { __tableName: T };
import { ConversationList } from "@/components/conversations/conversation-list";
import { MessageThread } from "@/components/conversations/message-thread";
import { MessageInput } from "@/components/conversations/message-input";
import { MessageSquare, Search } from "lucide-react";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";

export default function ConversationsPage() {
  const [selectedConversationId, setSelectedConversationId] =
    useState<Id<"conversations"> | null>(null);
  const [searchQuery, setSearchQuery] = useState("");

  const conversationsData = useQuery(api.conversations.list, {
    search: searchQuery || undefined,
  });

  // Extract items from the paginated response
  const conversations = useMemo(() => {
    return conversationsData?.items ?? [];
  }, [conversationsData]);

  const selectedConversation = useQuery(
    api.conversations.get,
    selectedConversationId ? { id: selectedConversationId } : "skip"
  );

  const messages = useQuery(
    api.messages.listByConversation,
    selectedConversationId
      ? { conversationId: selectedConversationId }
      : "skip"
  );

  const handleSelectConversation = useCallback(
    (id: Id<"conversations">) => {
      setSelectedConversationId(id);
    },
    []
  );

  const handleSearch = useCallback((query: string) => {
    setSearchQuery(query);
  }, []);

  return (
    <div className="flex h-full bg-zinc-50 dark:bg-zinc-950">
      {/* Left Panel - Conversation List */}
      <div
        className={cn(
          "flex h-full w-full flex-col border-r border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-900",
          "md:w-80 lg:w-96",
          selectedConversationId && "hidden md:flex"
        )}
      >
        {/* Search Header */}
        <div className="flex-shrink-0 border-b border-zinc-200 p-4 dark:border-zinc-800">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-400" />
            <Input
              type="text"
              placeholder="Search conversations..."
              value={searchQuery}
              onChange={(e) => handleSearch(e.target.value)}
              className="pl-9 bg-zinc-100 border-0 focus-visible:ring-1 focus-visible:ring-blue-500 dark:bg-zinc-800"
            />
          </div>
        </div>

        {/* Conversations List */}
        <div className="flex-1 overflow-y-auto">
          {conversationsData === undefined ? (
            <div className="flex h-full items-center justify-center">
              <div className="h-8 w-8 animate-spin rounded-full border-2 border-zinc-300 border-t-blue-500" />
            </div>
          ) : conversations.length === 0 ? (
            <div className="flex h-full flex-col items-center justify-center p-8 text-center">
              <MessageSquare className="mb-4 h-12 w-12 text-zinc-300 dark:text-zinc-600" />
              <h3 className="mb-2 font-medium text-zinc-900 dark:text-zinc-100">
                No conversations
              </h3>
              <p className="text-sm text-zinc-500 dark:text-zinc-400">
                {searchQuery
                  ? "No conversations match your search"
                  : "Start a conversation to get going"}
              </p>
            </div>
          ) : (
            <ConversationList
              conversations={conversations}
              selectedId={selectedConversationId}
              onSelect={handleSelectConversation}
            />
          )}
        </div>
      </div>

      {/* Right Panel - Message Thread */}
      <div
        className={cn(
          "flex h-full flex-1 flex-col bg-white dark:bg-zinc-900",
          !selectedConversationId && "hidden md:flex"
        )}
      >
        {selectedConversationId && selectedConversation ? (
          <>
            {/* Thread Header */}
            <div className="flex flex-shrink-0 items-center gap-3 border-b border-zinc-200 px-4 py-3 dark:border-zinc-800">
              {/* Back Button (Mobile) */}
              <button
                onClick={() => setSelectedConversationId(null)}
                className="rounded-lg p-2 text-zinc-600 hover:bg-zinc-100 md:hidden dark:text-zinc-400 dark:hover:bg-zinc-800"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={2}
                  stroke="currentColor"
                  className="h-5 w-5"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M15.75 19.5L8.25 12l7.5-7.5"
                  />
                </svg>
              </button>

              {/* Contact Info */}
              <div className="flex flex-1 items-center gap-3">
                <div className="relative h-10 w-10 shrink-0 overflow-hidden rounded-full bg-zinc-200 dark:bg-zinc-700">
                  {selectedConversation.contact?.avatarUrl ? (
                    <img
                      src={selectedConversation.contact.avatarUrl}
                      alt=""
                      className="h-full w-full object-cover"
                    />
                  ) : (
                    <div className="flex h-full w-full items-center justify-center text-sm font-medium text-zinc-600 dark:text-zinc-300">
                      {selectedConversation.contact?.firstName?.charAt(0) ||
                        selectedConversation.phoneNumber.charAt(0)}
                    </div>
                  )}
                  {/* Online indicator */}
                  <div className="absolute bottom-0 right-0 h-3 w-3 rounded-full border-2 border-white bg-green-500 dark:border-zinc-900" />
                </div>
                <div className="flex-1 min-w-0">
                  <h2 className="font-semibold text-zinc-900 dark:text-zinc-100 truncate">
                    {selectedConversation.contact
                      ? `${selectedConversation.contact.firstName || ""} ${selectedConversation.contact.lastName || ""}`.trim() ||
                        selectedConversation.phoneNumber
                      : selectedConversation.phoneNumber}
                  </h2>
                  <p className="text-sm text-zinc-500 dark:text-zinc-400">
                    {selectedConversation.isIMessage ? "iMessage" : "SMS"} •{" "}
                    {selectedConversation.phoneNumber}
                  </p>
                </div>
              </div>

              {/* AI Status Badge */}
              {selectedConversation.aiEnabled && (
                <div className="flex items-center gap-1.5 rounded-full bg-purple-100 px-2.5 py-1 text-xs font-medium text-purple-700 dark:bg-purple-900/30 dark:text-purple-400">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                    fill="currentColor"
                    className="h-3.5 w-3.5"
                  >
                    <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 17.93c-3.95-.49-7-3.85-7-7.93 0-.62.08-1.21.21-1.79L9 15v1c0 1.1.9 2 2 2v1.93zm6.9-2.54c-.26-.81-1-1.39-1.9-1.39h-1v-3c0-.55-.45-1-1-1H8v-2h2c.55 0 1-.45 1-1V7h2c1.1 0 2-.9 2-2v-.41c2.93 1.19 5 4.06 5 7.41 0 2.08-.8 3.97-2.1 5.39z" />
                  </svg>
                  AI Active
                </div>
              )}

              {/* Workflow Status Badge */}
              {selectedConversation.status === "workflow_active" && (
                <div className="flex items-center gap-1.5 rounded-full bg-blue-100 px-2.5 py-1 text-xs font-medium text-blue-700 dark:bg-blue-900/30 dark:text-blue-400">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                    fill="currentColor"
                    className="h-3.5 w-3.5"
                  >
                    <path
                      fillRule="evenodd"
                      d="M3 6a3 3 0 013-3h12a3 3 0 013 3v12a3 3 0 01-3 3H6a3 3 0 01-3-3V6zm4.5 7.5a.75.75 0 01.75.75v2.25a.75.75 0 01-1.5 0v-2.25a.75.75 0 01.75-.75zm3.75-1.5a.75.75 0 00-1.5 0v4.5a.75.75 0 001.5 0V12zm2.25-3a.75.75 0 01.75.75v6.75a.75.75 0 01-1.5 0V9.75A.75.75 0 0113.5 9zm3.75-1.5a.75.75 0 00-1.5 0v9a.75.75 0 001.5 0v-9z"
                      clipRule="evenodd"
                    />
                  </svg>
                  Workflow
                </div>
              )}
            </div>

            {/* Message Thread */}
            <MessageThread
              messages={messages || []}
              conversation={selectedConversation}
            />

            {/* Message Input */}
            <MessageInput
              conversationId={selectedConversationId}
              aiEnabled={selectedConversation.aiEnabled}
            />
          </>
        ) : (
          /* Empty State */
          <div className="flex h-full flex-col items-center justify-center p-8 text-center">
            <div className="mb-4 rounded-full bg-zinc-100 p-6 dark:bg-zinc-800">
              <MessageSquare className="h-12 w-12 text-zinc-400 dark:text-zinc-500" />
            </div>
            <h3 className="mb-2 text-xl font-semibold text-zinc-900 dark:text-zinc-100">
              Select a conversation
            </h3>
            <p className="max-w-sm text-zinc-500 dark:text-zinc-400">
              Choose a conversation from the list to view messages and continue
              the discussion.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
