"use client";

import { formatRelativeTime } from "@/lib/utils";
import { cn } from "@/lib/utils";

// Note: These types are generated by Convex. If not available, run `npx convex dev`
type Id<T extends string> = string & { __tableName: T };

interface Contact {
  _id: Id<"contacts">;
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  avatarUrl?: string;
}

interface ConversationWithContact {
  _id: Id<"conversations">;
  _creationTime: number;
  phoneNumber: string;
  sendblueNumber: string;
  contactId?: Id<"contacts">;
  status: "active" | "archived" | "workflow_active";
  isIMessage: boolean;
  aiEnabled: boolean;
  activeWorkflowId?: Id<"workflows">;
  messageCount: number;
  lastMessageAt: number;
  lastMessagePreview?: string;
  ownerId?: Id<"users">;
  createdAt: number;
  contact: Contact | null;
  unreadCount: number;
}

interface ConversationListProps {
  conversations: ConversationWithContact[];
  selectedId: Id<"conversations"> | null;
  onSelect: (id: Id<"conversations">) => void;
}

export function ConversationList({
  conversations,
  selectedId,
  onSelect,
}: ConversationListProps) {
  return (
    <div className="divide-y divide-zinc-100 dark:divide-zinc-800">
      {conversations.map((conversation) => (
        <ConversationItem
          key={conversation._id}
          conversation={conversation}
          isSelected={selectedId === conversation._id}
          onSelect={() => onSelect(conversation._id)}
        />
      ))}
    </div>
  );
}

interface ConversationItemProps {
  conversation: ConversationWithContact;
  isSelected: boolean;
  onSelect: () => void;
}

function ConversationItem({
  conversation,
  isSelected,
  onSelect,
}: ConversationItemProps) {
  const displayName = conversation.contact
    ? `${conversation.contact.firstName || ""} ${conversation.contact.lastName || ""}`.trim() ||
      conversation.phoneNumber
    : conversation.phoneNumber;

  const initials = conversation.contact
    ? `${conversation.contact.firstName?.charAt(0) || ""}${conversation.contact.lastName?.charAt(0) || ""}`.toUpperCase() ||
      conversation.phoneNumber.slice(-2)
    : conversation.phoneNumber.slice(-2);

  // Check for unread messages
  const hasUnread = conversation.unreadCount > 0;

  return (
    <button
      onClick={onSelect}
      className={cn(
        "flex w-full items-start gap-3 p-4 text-left transition-colors",
        "hover:bg-zinc-50 dark:hover:bg-zinc-800/50",
        isSelected && "bg-blue-50 hover:bg-blue-50 dark:bg-blue-900/20 dark:hover:bg-blue-900/20"
      )}
    >
      {/* Avatar */}
      <div className="relative flex-shrink-0">
        <div
          className={cn(
            "flex h-12 w-12 items-center justify-center rounded-full text-sm font-medium",
            conversation.contact?.avatarUrl
              ? ""
              : isSelected
                ? "bg-blue-100 text-blue-700 dark:bg-blue-800 dark:text-blue-200"
                : "bg-zinc-200 text-zinc-600 dark:bg-zinc-700 dark:text-zinc-300"
          )}
        >
          {conversation.contact?.avatarUrl ? (
            <img
              src={conversation.contact.avatarUrl}
              alt={displayName}
              className="h-full w-full rounded-full object-cover"
            />
          ) : (
            initials
          )}
        </div>
        {/* Message type indicator */}
        <div
          className={cn(
            "absolute -bottom-0.5 -right-0.5 flex h-5 w-5 items-center justify-center rounded-full border-2 border-white dark:border-zinc-900",
            conversation.isIMessage
              ? "bg-blue-500"
              : "bg-green-500"
          )}
        >
          <span className="text-[10px] font-medium text-white">
            {conversation.isIMessage ? "i" : "S"}
          </span>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 min-w-0">
        <div className="flex items-center justify-between gap-2">
          <span
            className={cn(
              "truncate font-medium",
              isSelected
                ? "text-blue-900 dark:text-blue-100"
                : "text-zinc-900 dark:text-zinc-100"
            )}
          >
            {displayName}
          </span>
          <span className="flex-shrink-0 text-xs text-zinc-500 dark:text-zinc-400">
            {formatRelativeTime(conversation.lastMessageAt)}
          </span>
        </div>

        <div className="mt-0.5 flex items-center gap-2">
          <p className="flex-1 truncate text-sm text-zinc-500 dark:text-zinc-400">
            {conversation.lastMessagePreview || "No messages yet"}
          </p>

          {/* Status indicators */}
          <div className="flex items-center gap-1.5 flex-shrink-0">
            {/* AI indicator */}
            {conversation.aiEnabled && (
              <div className="flex h-5 w-5 items-center justify-center rounded-full bg-purple-100 dark:bg-purple-900/40">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 24 24"
                  fill="currentColor"
                  className="h-3 w-3 text-purple-600 dark:text-purple-400"
                >
                  <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 17.93c-3.95-.49-7-3.85-7-7.93 0-.62.08-1.21.21-1.79L9 15v1c0 1.1.9 2 2 2v1.93zm6.9-2.54c-.26-.81-1-1.39-1.9-1.39h-1v-3c0-.55-.45-1-1-1H8v-2h2c.55 0 1-.45 1-1V7h2c1.1 0 2-.9 2-2v-.41c2.93 1.19 5 4.06 5 7.41 0 2.08-.8 3.97-2.1 5.39z" />
                </svg>
              </div>
            )}

            {/* Workflow indicator */}
            {conversation.status === "workflow_active" && (
              <div className="flex h-5 w-5 items-center justify-center rounded-full bg-blue-100 dark:bg-blue-900/40">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 24 24"
                  fill="currentColor"
                  className="h-3 w-3 text-blue-600 dark:text-blue-400"
                >
                  <path
                    fillRule="evenodd"
                    d="M3 6a3 3 0 013-3h12a3 3 0 013 3v12a3 3 0 01-3 3H6a3 3 0 01-3-3V6zm4.5 7.5a.75.75 0 01.75.75v2.25a.75.75 0 01-1.5 0v-2.25a.75.75 0 01.75-.75zm3.75-1.5a.75.75 0 00-1.5 0v4.5a.75.75 0 001.5 0V12zm2.25-3a.75.75 0 01.75.75v6.75a.75.75 0 01-1.5 0V9.75A.75.75 0 0113.5 9zm3.75-1.5a.75.75 0 00-1.5 0v9a.75.75 0 001.5 0v-9z"
                    clipRule="evenodd"
                  />
                </svg>
              </div>
            )}

            {/* Unread indicator */}
            {hasUnread && (
              <div className="flex h-5 min-w-5 items-center justify-center rounded-full bg-blue-500 px-1.5">
                <span className="text-[10px] font-bold text-white">
                  {conversation.unreadCount > 99 ? "99+" : conversation.unreadCount}
                </span>
              </div>
            )}
          </div>
        </div>
      </div>
    </button>
  );
}
