"use client";

import { useEffect, useRef, useState } from "react";
import { cn } from "@/lib/utils";
import { Check, CheckCheck, AlertCircle, Clock, Sparkles } from "lucide-react";

// Note: These types are generated by Convex. If not available, run `npx convex dev`
type Id<T extends string> = string & { __tableName: T };

interface Contact {
  _id: Id<"contacts">;
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  avatarUrl?: string;
}

interface Message {
  _id: Id<"messages">;
  _creationTime: number;
  conversationId: Id<"conversations">;
  direction: "inbound" | "outbound";
  content: string;
  mediaUrl?: string;
  status: "pending" | "sent" | "delivered" | "read" | "failed";
  messageHandle?: string;
  service?: "iMessage" | "SMS";
  errorMessage?: string;
  aiGenerated?: boolean;
  workflowId?: Id<"workflows">;
  timestamp: number;
}

interface ConversationWithContact {
  _id: Id<"conversations">;
  phoneNumber: string;
  isIMessage: boolean;
  aiEnabled: boolean;
  contact: Contact | null;
}

interface MessageThreadProps {
  messages: Message[];
  conversation: ConversationWithContact;
}

export function MessageThread({ messages, conversation }: MessageThreadProps) {
  const scrollRef = useRef<HTMLDivElement>(null);
  const [showTypingIndicator, setShowTypingIndicator] = useState(false);

  // Auto-scroll to bottom when new messages arrive
  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages]);

  // Group messages by date
  const groupedMessages = groupMessagesByDate(messages);

  return (
    <div
      ref={scrollRef}
      className="flex-1 overflow-y-auto px-4 py-4"
      style={{
        backgroundImage: `radial-gradient(circle at 1px 1px, rgb(229 231 235 / 0.4) 1px, transparent 0)`,
        backgroundSize: "24px 24px",
      }}
    >
      <div className="mx-auto max-w-3xl space-y-4">
        {groupedMessages.map((group) => (
          <div key={group.date}>
            {/* Date separator */}
            <div className="relative my-6 flex items-center justify-center">
              <div className="absolute inset-0 flex items-center">
                <div className="w-full border-t border-zinc-200 dark:border-zinc-700" />
              </div>
              <div className="relative bg-zinc-50 px-3 dark:bg-zinc-950">
                <span className="text-xs font-medium text-zinc-500 dark:text-zinc-400">
                  {group.date}
                </span>
              </div>
            </div>

            {/* Messages for this date */}
            <div className="space-y-2">
              {group.messages.map((message, index) => {
                const prevMessage = index > 0 ? group.messages[index - 1] : null;
                const nextMessage =
                  index < group.messages.length - 1
                    ? group.messages[index + 1]
                    : null;

                const isFirstInGroup =
                  !prevMessage || prevMessage.direction !== message.direction;
                const isLastInGroup =
                  !nextMessage || nextMessage.direction !== message.direction;

                return (
                  <MessageBubble
                    key={message._id}
                    message={message}
                    isFirstInGroup={isFirstInGroup}
                    isLastInGroup={isLastInGroup}
                    contactName={
                      conversation.contact
                        ? `${conversation.contact.firstName || ""} ${conversation.contact.lastName || ""}`.trim()
                        : conversation.phoneNumber
                    }
                  />
                );
              })}
            </div>
          </div>
        ))}

        {/* Typing indicator */}
        {showTypingIndicator && (
          <div className="flex items-end gap-2">
            <div className="h-8 w-8 rounded-full bg-zinc-200 dark:bg-zinc-700" />
            <div className="rounded-2xl rounded-bl-md bg-zinc-200 px-4 py-3 dark:bg-zinc-700">
              <div className="flex gap-1">
                <div className="h-2 w-2 animate-bounce rounded-full bg-zinc-400 [animation-delay:-0.3s]" />
                <div className="h-2 w-2 animate-bounce rounded-full bg-zinc-400 [animation-delay:-0.15s]" />
                <div className="h-2 w-2 animate-bounce rounded-full bg-zinc-400" />
              </div>
            </div>
          </div>
        )}

        {/* Empty state */}
        {messages.length === 0 && (
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <div className="mb-4 rounded-full bg-zinc-100 p-4 dark:bg-zinc-800">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                fill="currentColor"
                className="h-8 w-8 text-zinc-400"
              >
                <path
                  fillRule="evenodd"
                  d="M4.848 2.771A49.144 49.144 0 0112 2.25c2.43 0 4.817.178 7.152.52 1.978.292 3.348 2.024 3.348 3.97v6.02c0 1.946-1.37 3.678-3.348 3.97a48.901 48.901 0 01-3.476.383.39.39 0 00-.297.17l-2.755 4.133a.75.75 0 01-1.248 0l-2.755-4.133a.39.39 0 00-.297-.17 48.9 48.9 0 01-3.476-.384c-1.978-.29-3.348-2.024-3.348-3.97V6.741c0-1.946 1.37-3.68 3.348-3.97z"
                  clipRule="evenodd"
                />
              </svg>
            </div>
            <h3 className="mb-1 font-medium text-zinc-900 dark:text-zinc-100">
              No messages yet
            </h3>
            <p className="text-sm text-zinc-500 dark:text-zinc-400">
              Start the conversation by sending a message below.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}

interface MessageBubbleProps {
  message: Message;
  isFirstInGroup: boolean;
  isLastInGroup: boolean;
  contactName: string;
}

function MessageBubble({
  message,
  isFirstInGroup,
  isLastInGroup,
  contactName,
}: MessageBubbleProps) {
  const isOutbound = message.direction === "outbound";
  const timestamp = new Date(message.timestamp);

  const getBubbleRadius = () => {
    if (isOutbound) {
      if (isFirstInGroup && isLastInGroup) return "rounded-2xl";
      if (isFirstInGroup) return "rounded-2xl rounded-br-md";
      if (isLastInGroup) return "rounded-2xl rounded-tr-md";
      return "rounded-2xl rounded-r-md";
    } else {
      if (isFirstInGroup && isLastInGroup) return "rounded-2xl";
      if (isFirstInGroup) return "rounded-2xl rounded-bl-md";
      if (isLastInGroup) return "rounded-2xl rounded-tl-md";
      return "rounded-2xl rounded-l-md";
    }
  };

  return (
    <div
      className={cn(
        "flex items-end gap-2",
        isOutbound ? "flex-row-reverse" : "flex-row"
      )}
    >
      {/* Avatar for inbound messages */}
      {!isOutbound && isLastInGroup && (
        <div className="mb-5 h-8 w-8 flex-shrink-0 rounded-full bg-zinc-200 dark:bg-zinc-700">
          <div className="flex h-full w-full items-center justify-center text-xs font-medium text-zinc-600 dark:text-zinc-300">
            {contactName.charAt(0).toUpperCase()}
          </div>
        </div>
      )}
      {!isOutbound && !isLastInGroup && <div className="w-8" />}

      {/* Message content */}
      <div
        className={cn(
          "group relative max-w-[75%]",
          isOutbound ? "items-end" : "items-start"
        )}
      >
        {/* AI indicator */}
        {message.aiGenerated && isFirstInGroup && (
          <div
            className={cn(
              "mb-1 flex items-center gap-1 text-xs text-purple-600 dark:text-purple-400",
              isOutbound ? "justify-end" : "justify-start"
            )}
          >
            <Sparkles className="h-3 w-3" />
            <span>AI Response</span>
          </div>
        )}

        {/* Bubble */}
        <div
          className={cn(
            "relative px-4 py-2.5 shadow-sm",
            getBubbleRadius(),
            isOutbound
              ? message.status === "failed"
                ? "bg-red-500 text-white"
                : "bg-blue-500 text-white"
              : "bg-zinc-200 text-zinc-900 dark:bg-zinc-700 dark:text-zinc-100"
          )}
        >
          {/* Media attachment */}
          {message.mediaUrl && (
            <div className="mb-2 overflow-hidden rounded-lg">
              <img
                src={message.mediaUrl}
                alt="Attachment"
                className="max-w-full cursor-pointer transition-opacity hover:opacity-90"
                onClick={() => window.open(message.mediaUrl, "_blank")}
              />
            </div>
          )}

          {/* Message text */}
          <p className="whitespace-pre-wrap break-words text-[15px] leading-relaxed">
            {message.content}
          </p>
        </div>

        {/* Timestamp and status */}
        {isLastInGroup && (
          <div
            className={cn(
              "mt-1 flex items-center gap-1.5 text-xs text-zinc-500 dark:text-zinc-400",
              isOutbound ? "justify-end" : "justify-start"
            )}
          >
            <span>
              {timestamp.toLocaleTimeString("en-US", {
                hour: "numeric",
                minute: "2-digit",
                hour12: true,
              })}
            </span>

            {/* Status indicator for outbound messages */}
            {isOutbound && (
              <span className="flex items-center">
                {message.status === "pending" && (
                  <Clock className="h-3 w-3 text-zinc-400" />
                )}
                {message.status === "sent" && (
                  <Check className="h-3.5 w-3.5 text-zinc-400" />
                )}
                {message.status === "delivered" && (
                  <CheckCheck className="h-3.5 w-3.5 text-zinc-400" />
                )}
                {message.status === "read" && (
                  <CheckCheck className="h-3.5 w-3.5 text-blue-500" />
                )}
                {message.status === "failed" && (
                  <AlertCircle className="h-3.5 w-3.5 text-red-500" />
                )}
              </span>
            )}

            {/* Service indicator */}
            {message.service && (
              <span
                className={cn(
                  "rounded px-1 text-[10px] font-medium",
                  message.service === "iMessage"
                    ? "bg-blue-100 text-blue-600 dark:bg-blue-900/40 dark:text-blue-400"
                    : "bg-green-100 text-green-600 dark:bg-green-900/40 dark:text-green-400"
                )}
              >
                {message.service}
              </span>
            )}
          </div>
        )}

        {/* Error message */}
        {message.status === "failed" && message.errorMessage && (
          <p className="mt-1 text-xs text-red-500 dark:text-red-400">
            {message.errorMessage}
          </p>
        )}
      </div>
    </div>
  );
}

// Helper function to group messages by date
function groupMessagesByDate(messages: Message[]) {
  const groups: { date: string; messages: Message[] }[] = [];

  messages.forEach((message) => {
    const messageDate = new Date(message.timestamp);
    const today = new Date();
    const yesterday = new Date(today);
    yesterday.setDate(yesterday.getDate() - 1);

    let dateString: string;
    if (messageDate.toDateString() === today.toDateString()) {
      dateString = "Today";
    } else if (messageDate.toDateString() === yesterday.toDateString()) {
      dateString = "Yesterday";
    } else {
      dateString = messageDate.toLocaleDateString("en-US", {
        weekday: "long",
        month: "long",
        day: "numeric",
      });
    }

    const existingGroup = groups.find((g) => g.date === dateString);
    if (existingGroup) {
      existingGroup.messages.push(message);
    } else {
      groups.push({ date: dateString, messages: [message] });
    }
  });

  return groups;
}
