"use client";

import { useState, useRef, useCallback, KeyboardEvent } from "react";
import { useMutation, useAction, useQuery } from "convex/react";
import { api } from "../../../convex/_generated/api";
import { cn } from "@/lib/utils";
import { Send, Sparkles, Paperclip, Smile, AlertCircle } from "lucide-react";
import { Button } from "@/components/ui/button";

// Note: Id type is generated by Convex. If not available, run `npx convex dev`
type Id<T extends string> = string & { __tableName: T };

interface MessageInputProps {
  conversationId: Id<"conversations">;
  aiEnabled: boolean;
  maxLength?: number;
  disabled?: boolean;
}

export function MessageInput({
  conversationId,
  aiEnabled,
  maxLength = 1600,
  disabled = false,
}: MessageInputProps) {
  const [message, setMessage] = useState("");
  const [isSending, setIsSending] = useState(false);
  const [showAIToggle, setShowAIToggle] = useState(false);
  const [sendError, setSendError] = useState<string | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Check if Sendblue is configured
  const sendblueStatus = useQuery(api.sendblue.isConfigured);
  const isSendblueConfigured = sendblueStatus?.isConnected ?? false;

  // Use Sendblue action if configured, otherwise fall back to local mutation
  // const sendViaSendblue = useAction(api.sendblue.sendMessage);
  // const sendMessageLocal = useMutation(api.messages.send);
  // const toggleAI = useMutation(api.conversations.toggleAI);

  const characterCount = message.length;
  const isOverLimit = characterCount > maxLength;
  const canSend = message.trim().length > 0 && !isOverLimit && !isSending && !disabled;

  // Auto-resize textarea
  const handleInput = useCallback((value: string) => {
    setMessage(value);

    // Auto-resize
    if (textareaRef.current) {
      textareaRef.current.style.height = "auto";
      textareaRef.current.style.height = `${Math.min(textareaRef.current.scrollHeight, 200)}px`;
    }
  }, []);

  // Handle send
  const handleSend = useCallback(async () => {
    if (!canSend) return;

    const content = message.trim();
    setIsSending(true);
    setMessage("");
    setSendError(null);

    // Reset textarea height
    if (textareaRef.current) {
      textareaRef.current.style.height = "auto";
    }

    try {
      // if (isSendblueConfigured) {
      //   // Send via Sendblue API
      //   const result = await sendViaSendblue({
      //     conversationId,
      //     content,
      //   });

      //   if (!result.success) {
      //     setSendError(result.error || "Failed to send message");
      //     // Message is already saved in pending/failed state by the action
      //   }
      // } else {
      //   // Fall back to local save only (no actual SMS sending)
      //   await sendMessageLocal({
      //     conversationId,
      //     content,
      //   });
      // }
      setSendError("Message sending not configured. Please add SendBlue integration.");
    } catch (error) {
      console.error("Failed to send message:", error);
      const errorMessage = error instanceof Error ? error.message : "Failed to send message";
      setSendError(errorMessage);
      // Restore message on error
      setMessage(content);
    } finally {
      setIsSending(false);
      textareaRef.current?.focus();
    }
  }, [canSend, message, conversationId, isSendblueConfigured]);

  // Handle keyboard shortcuts
  const handleKeyDown = useCallback(
    (e: KeyboardEvent<HTMLTextAreaElement>) => {
      // Send on Enter (without Shift)
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        handleSend();
      }
    },
    [handleSend]
  );

  // Handle AI toggle
  const handleToggleAI = useCallback(async () => {
    // try {
    //   await toggleAI({ id: conversationId });
    // } catch (error) {
    //   console.error("Failed to toggle AI:", error);
    // }
    setShowAIToggle(false);
  }, [conversationId]);

  return (
    <div className="flex-shrink-0 border-t border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900">
      {/* Error Banner */}
      {sendError && (
        <div className="mb-3 flex items-center gap-2 rounded-lg bg-red-50 px-4 py-3 dark:bg-red-900/20">
          <AlertCircle className="h-4 w-4 flex-shrink-0 text-red-600 dark:text-red-400" />
          <span className="flex-1 text-sm text-red-800 dark:text-red-200">
            {sendError}
          </span>
          <button
            onClick={() => setSendError(null)}
            className="text-red-600 hover:text-red-800 dark:text-red-400 dark:hover:text-red-200"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-4 w-4"
              viewBox="0 0 20 20"
              fill="currentColor"
            >
              <path
                fillRule="evenodd"
                d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                clipRule="evenodd"
              />
            </svg>
          </button>
        </div>
      )}

      {/* Sendblue Status Warning */}
      {sendblueStatus && !sendblueStatus.isConnected && (
        <div className="mb-3 flex items-center gap-2 rounded-lg bg-amber-50 px-4 py-2 dark:bg-amber-900/20">
          <AlertCircle className="h-4 w-4 flex-shrink-0 text-amber-600 dark:text-amber-400" />
          <span className="text-xs text-amber-800 dark:text-amber-200">
            Sendblue not configured. Messages will be saved locally but not sent.
          </span>
        </div>
      )}

      {/* AI Toggle Popup */}
      {showAIToggle && (
        <div className="mb-3 flex items-center justify-between rounded-lg bg-purple-50 px-4 py-3 dark:bg-purple-900/20">
          <div className="flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-purple-600 dark:text-purple-400" />
            <span className="text-sm font-medium text-purple-900 dark:text-purple-100">
              {aiEnabled ? "AI responses are enabled" : "Enable AI responses?"}
            </span>
          </div>
          <div className="flex items-center gap-2">
            <Button
              variant="ghost"
              size="sm"
              onClick={() => setShowAIToggle(false)}
              className="text-purple-600 hover:bg-purple-100 dark:text-purple-400 dark:hover:bg-purple-900/30"
            >
              Cancel
            </Button>
            <Button
              size="sm"
              onClick={handleToggleAI}
              className={cn(
                aiEnabled
                  ? "bg-zinc-600 hover:bg-zinc-700"
                  : "bg-purple-600 hover:bg-purple-700"
              )}
            >
              {aiEnabled ? "Disable AI" : "Enable AI"}
            </Button>
          </div>
        </div>
      )}

      {/* Input Area */}
      <div className="flex items-end gap-2">
        {/* Attachment Button */}
        <button
          type="button"
          className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full text-zinc-500 transition-colors hover:bg-zinc-100 hover:text-zinc-700 dark:text-zinc-400 dark:hover:bg-zinc-800 dark:hover:text-zinc-300"
          title="Add attachment"
        >
          <Paperclip className="h-5 w-5" />
        </button>

        {/* Text Input */}
        <div className="relative flex-1">
          <textarea
            ref={textareaRef}
            value={message}
            onChange={(e) => handleInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Type a message..."
            disabled={disabled || isSending}
            rows={1}
            className={cn(
              "w-full resize-none rounded-2xl border bg-zinc-100 px-4 py-2.5 pr-12 text-[15px] leading-relaxed placeholder-zinc-400 transition-colors",
              "focus:border-blue-500 focus:bg-white focus:outline-none focus:ring-2 focus:ring-blue-500/20",
              "dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-100 dark:placeholder-zinc-500 dark:focus:bg-zinc-800",
              isOverLimit && "border-red-500 focus:border-red-500 focus:ring-red-500/20",
              disabled && "cursor-not-allowed opacity-50"
            )}
            style={{ maxHeight: "200px" }}
          />

          {/* Emoji Button */}
          <button
            type="button"
            className="absolute bottom-2.5 right-3 text-zinc-400 transition-colors hover:text-zinc-600 dark:text-zinc-500 dark:hover:text-zinc-400"
            title="Add emoji"
          >
            <Smile className="h-5 w-5" />
          </button>
        </div>

        {/* AI Toggle Button */}
        <button
          type="button"
          onClick={() => setShowAIToggle(!showAIToggle)}
          className={cn(
            "flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full transition-colors",
            aiEnabled
              ? "bg-purple-100 text-purple-600 hover:bg-purple-200 dark:bg-purple-900/40 dark:text-purple-400 dark:hover:bg-purple-900/60"
              : "text-zinc-400 hover:bg-zinc-100 hover:text-zinc-600 dark:text-zinc-500 dark:hover:bg-zinc-800 dark:hover:text-zinc-400"
          )}
          title={aiEnabled ? "AI is enabled" : "Toggle AI"}
        >
          <Sparkles className="h-5 w-5" />
        </button>

        {/* Send Button */}
        <button
          type="button"
          onClick={handleSend}
          disabled={!canSend}
          className={cn(
            "flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full transition-all",
            canSend
              ? "bg-blue-500 text-white hover:bg-blue-600 active:scale-95"
              : "cursor-not-allowed bg-zinc-200 text-zinc-400 dark:bg-zinc-700 dark:text-zinc-500"
          )}
          title="Send message"
        >
          {isSending ? (
            <div className="h-5 w-5 animate-spin rounded-full border-2 border-white border-t-transparent" />
          ) : (
            <Send className="h-5 w-5" />
          )}
        </button>
      </div>

      {/* Character Count */}
      <div className="mt-2 flex items-center justify-between px-1">
        <div className="text-xs text-zinc-400 dark:text-zinc-500">
          Press <kbd className="rounded bg-zinc-200 px-1 py-0.5 font-mono text-[10px] dark:bg-zinc-700">Enter</kbd> to send,{" "}
          <kbd className="rounded bg-zinc-200 px-1 py-0.5 font-mono text-[10px] dark:bg-zinc-700">Shift+Enter</kbd> for new line
        </div>
        <div
          className={cn(
            "text-xs font-medium transition-colors",
            isOverLimit
              ? "text-red-500"
              : characterCount > maxLength * 0.9
                ? "text-amber-500"
                : "text-zinc-400 dark:text-zinc-500"
          )}
        >
          {characterCount} / {maxLength}
        </div>
      </div>
    </div>
  );
}
